ARCHS = armv7 arm64

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Cr4shedSB
Cr4shedSB_FILES = Tweak.xm
Cr4shedSB_FRAMEWORKS = UIKit
Cr4shedSB_CFLAGS = -fobjc-arc
Cr4shedSB_PRIVATE_FRAMEWORKS = AppSupport
Cr4shedSB_LIBRARIES = rocketbootstrap

include $(THEOS_MAKE_PATH)/tweak.mk
