#!/usr/bin/env sh
echo "Killing ReportCrash..."
killall -9 ReportCrash 2> /dev/null
echo "Killing ReportMemoryException..."
killall -9 ReportMemoryException 2> /dev/null
echo "Starting cr4shedd..."
PREFIX=
if [ -L "/var/jb" ] && [ -d "/var/jb" ]; then
    PREFIX="/var/jb"
fi
chown root:wheel "$PREFIX/usr/libexec/cr4shedd"
chmod 755 "$PREFIX/usr/libexec/cr4shedd"
chown root:wheel "$PREFIX/Library/LaunchDaemons/com.muirey03.cr4shedd.plist"
chmod 644 "$PREFIX/Library/LaunchDaemons/com.muirey03.cr4shedd.plist"
launchctl load "$PREFIX/Library/LaunchDaemons/com.muirey03.cr4shedd.plist" 2> /dev/null
echo "Done!"
exit 0
