#!/bin/sh
echo "Killing cr4shedd..."
launchctl unload /Library/LaunchDaemons/com.muirey03.cr4shedd.plist 2> /dev/null
echo "Killing ReportCrash..."
killall -9 ReportCrash 2> /dev/null
echo "Killing ReportMemoryException..."
killall -9 ReportMemoryException 2> /dev/null
echo "Done!"
exit 0
